export const ADD_TO_CART = "ADD_TO_CART";


export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_RESET = "ADD_TO_CART_RESET";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";

export const MY_CART_REQUEST = "MY_CART_REQUEST";
export const MY_CART_SUCCESS = "MY_CART_SUCCESS";
export const MY_CART_FAIL = "MY_CART_FAIL";

export const DELETE_CART_REQUEST = "DELETE_CART_REQUEST";
export const DELETE_CART_SUCCESS = "DELETE_CART_SUCCESS";
export const DELETE_CART_RESET = "DELETE_CART_RESET";
export const DELETE_CART_FAIL = "DELETE_CART_FAIL";

export const ADD_SHIPPING_REQUEST = "ADD_SHIPPING_REQUEST";
export const ADD_SHIPPING_SUCCESS = "ADD_SHIPPING_SUCCESS";
export const ADD_SHIPPING_FAIL = "ADD_SHIPPING_FAIL";

export const GET_SHIPPING_REQUEST = "GET_SHIPPING_REQUEST";
export const GET_SHIPPING_SUCCESS = "GET_SHIPPING_SUCCESS";
export const GET_SHIPPING_FAIL = "GET_SHIPPING_FAIL";




export const CLEAR_ERRORS = "CLEAR_ERRORS";