export const NEW_CATEGORY_REQUEST = "NEW_CATEGORY_REQUEST" ;
export const NEW_CATEGORY_SUCCESS = "NEW_CATEGORY_SUCCESS" ;
export const NEW_CATEGORY_RESET = "NEW_CATEGORY_RESET" ;
export const NEW_CATEGORY_FAIL =    "NEW_CATEGORY_FAIL" ;


export const ALL_CATEGORIES_REQUEST = "ALL_CATEGORIES_REQUEST" ;
export const ALL_CATEGORIES_SUCCESS = "ALL_CATEGORIES_SUCCESS" ;
export const ALL_CATEGORIES_FAIL =    "ALL_CATEGORIES_FAIL" ;

export const GET_CATEGORY_REQUEST = "GET_CATEGORY_REQUEST" ;
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS" ;
export const GET_CATEGORY_FAIL =    "GET_CATEGORY_FAIL" ;

export const UPDATE_CATEGORY_REQUEST = "UPDATE_CATEGORY_REQUEST" ;
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS" ;
export const UPDATE_CATEGORY_RESET = "UPDATE_CATEGORY_RESET" ;
export const UPDATE_CATEGORY_FAIL =    "UPDATE_CATEGORY_FAIL" ;

export const DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST" ;
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS" ;
export const DELETE_CATEGORY_RESET = "DELETE_CATEGORY_RESET" ;
export const DELETE_CATEGORY_FAIL =    "DELETE_CATEGORY_FAIL" ;


export const CLEAR_ERRORS = "CLEAR_ERRORS";