export const ADD_TO_WISHLIST_REQUEST = "ADD_TO_WISHLIST_REQUEST";
export const ADD_TO_WISHLIST_SUCCESS = "ADD_TO_WISHLIST_SUCCESS";
export const ADD_TO_WISHLIST_RESET = "ADD_TO_WISHLIST_RESET";
export const ADD_TO_WISHLIST_FAIL = "ADD_TO_WISHLIST_FAIL";

export const DELETE_WISHLIST_REQUEST = "DELETE_WISHLIST_REQUEST";
export const DELETE_WISHLIST_SUCCESS = "DELETE_WISHLIST_SUCCESS";
export const DELETE_WISHLIST_RESET = "DELETE_WISHLIST_RESET";
export const DELETE_WISHLIST_FAIL = "DELETE_WISHLIST_FAIL";

export const MY_WISHLIST_REQUEST = "MY_WISHLIST_REQUEST";
export const MY_WISHLIST_SUCCESS = "MY_WISHLIST_SUCCESS";
export const MY_WISHLIST_FAIL = "MY_WISHLIST_FAIL";



export const CLEAR_ERRORS = "CLEAR_ERRORS";